# config.py
#
# All parameters global variables are
# defined here and are to be referenced
# in other files

# COLORS
COLOR_BLUE_LIKE="#0063b1"
COLOR_ORANGE_LIKE="#ef7b11"
COLOR_GRAY_LIKE="#2d3447"
COLOR_WHITE="white"
COLOR_BLACK="black"
COLOR_RUBY="#f66"
COLOR_GOLD="gold"
COLOR_GHOST_WHITE="ghost white"

# APPLICATION SETTINGS
APP_TITLE="Démonstrateur de véhicules connectés V2X"
BUTTON_BG_COLOR_IDLE=COLOR_BLUE_LIKE 
BUTTON_FG_COLOR_IDLE=COLOR_WHITE
BUTTON_BG_COLOR_ACTIVE=COLOR_ORANGE_LIKE
BUTTON_FG_COLOR_ACTIVE=COLOR_WHITE
SCALE_BG_COLOR_IDLE=COLOR_BLUE_LIKE 
SCALE_FG_COLOR_IDLE=COLOR_WHITE 
SCALE_BG_COLOR_ACTIVE=COLOR_ORANGE_LIKE
LABEL_BG_COLOR=COLOR_GHOST_WHITE
CARS = [
        "Tout le monde",
        "Voiture 1",
        "Voiture 2",
        "Voiture 3",
        "Voiture 4",
        "Voiture 5",
        "Voiture 6",
        "Voiture 7"
    ]

# MAIN WINDOW SETTINGS
WINDOW_WIDTH=1100      # In pixels
WINDOW_HEIGHT=780     # In pixels
WINDOW_BG_COLOR=COLOR_GRAY_LIKE

# TAB SETTINGS
TAB_FRAME_BG_COLOR=COLOR_GHOST_WHITE
TAB_HEADER_BG_COLOR_IDLE=COLOR_BLUE_LIKE
TAB_HEADER_BG_COLOR_SELECTED=TAB_FRAME_BG_COLOR
TAB_HEADER_BG_COLOR_ACTIVE=COLOR_ORANGE_LIKE 
TAB_HEADER_FG_COLOR_IDLE=COLOR_WHITE
TAB_HEADER_FG_COLOR_SELECTED=COLOR_BLACK
TAB_HEADER_FG_COLOR_ACTIVE=COLOR_WHITE 
MAIN_TAB_NAME="Démonstrateur"
CONFIG_TAB_NAME="Configuration"
NOTEBOOK_PADX=30
NOTEBOOK_PADY=20

# CONTROL FRAME SETTINGS
CONTROL_FRAME_BG_COLOR=COLOR_GHOST_WHITE
CONTROL_FRAME_PADX=25
CONTROL_FRAME_PADY=(10, 5)
CONTROL_FRAME_BORDER_COLOR=COLOR_GRAY_LIKE
CONTROL_FRAME_BORDER_THICKNESS=5

# CONSOLE SETTINGS
CONSOLE_HEIGHT=20 # In number of lines
CONSOLE_WIDTH=15 # In number of characters
CONSOLE_BG_COLOR=WINDOW_BG_COLOR
CONSOLE_PADX=25
CONSOLE_PADY=5
CONSOLE_MAIN_LINE_BG_COLOR=COLOR_GRAY_LIKE
CONSOLE_MAIN_LINE_FG_COLOR=COLOR_WHITE
CONSOLE_MAIN_LINE_FONT=("Hack Regular", 12)
CONSOLE_ALERT_LINE_BG_COLOR="light goldenrod"
CONSOLE_ALERT_LINE_FG_COLOR="firebrick1"
CONSOLE_ALERT_LINE_FONT=("Hack Regular", 12)

# POINTS SETTINGS
POINT_DIAMETER=10
POINT_OUTLINE_COLOR=COLOR_GOLD
POINT_FILL_COLOR=COLOR_RUBY

# MAP SETTINS
MAP_HEIGHT=300 # In pixels
MAP_WIDTH=300
MAP_BG_COLOR=COLOR_GRAY_LIKE
MAP_GRADUATION_UNIT=20 # In pixels
MAP_PADX=(5, 25)
MAP_PADY=(5, 10)
MAP_ORIGIN_COLOR=COLOR_WHITE
MAP_DIVISION_LINE=6 # Small line defining a graduation unit

